### ISSUE TITLE
Response headers missing when using builder API

### ISSUE THREAD

**Issue by timwebster9** [thejamesthomas/javabank#5]
Hi,

Cool project..:-)

I think I found a problem when you build an imposter with response headers using the builder API.  Basically they don't end up in the JSON object.

if you look at Is.withHeaders() method, the headers passed in don't make it into the HEADERS in the 'data' Map.  I think it's the ones in data that end up in the JSON object.  If I change that method to add the passed-in headers into the headers in 'data', it works.

I could be doing something wrong, but if you print out the imposter in ImposterBuilderTest.shouldBuildAnHttpImposterWithAResponse() you'll see the 'plain/text' header is missing in the response.  Although the test passes as it's just looking at the Is  object.

I wasn't sure about the 'connection close' header (whether or not it was always supposed to be there), so held back on the pull request...

**Comment by thejamesthomas** [comment]
Hey! Sorry for the late reply, I've been a bit busy the past few weeks. :-)

It also looks like the commit that fixes this issue is in the PR you opened on creating responses from files. Both commits look great, so I'll accept the PR and I guess close this issue as fixed. Thanks for the contribution!

**Comment by timwebster9** [comment]
OK no problem...:-)

I also had a go with your Javabank Maven Plugin.  It didn't quite work with Windows (do you use a Mac?) but I got it working with a few tweaks, plus I added a StopMojo for shutting it down.  If you're interested I can submit a pull request / issue for that as well...
