### ISSUE TITLE
sha1 for javabank-all-0.2.2.pom is wrong

### ISSUE THREAD

**Issue by ajhcpt** [thejamesthomas/javabank#9]
Hi, the hash computed in javabank-all-0.2.2.pom.sha1 is wrong. The dependency can't be added to a project while this is incorrect.

Thanks,
Andrew

**Comment by thejamesthomas** [comment]
Hey Andrew,

Thanks for the report. Sorry for the delayed reply. Fixing the build so it properly signs and versions things was something I had been working on when I managed to scrape together the spare time to do so. I believe I've got things working mostly the way I want them to now.

I just pushed out version 0.4.7 to Central. It doesn't show up in any of the repo search engines yet, but it should be there shortly. Just to be sure it was fixed, I went ahead and created a quick test project, and I was able to import 0.4.7 successfully. So this should now be fixed.

Thanks again,
James
